### ISSUE TITLE
HMAC-SHA1 Signature Method

### ISSUE THREAD

**Issue by johaywood** [Medisana/vitadock-api#9]
Is there a plan to allow HMAC-SHA1 for generating the OAuth Signature? The defacto Ruby OAuth client doesn't support HMAC-SHA256 or PLAINTEXT, which makes it somewhat tedious to integrate.

**Comment by ClemensLode** [comment]
Hi johaywood,

Unfortunately, SHA-1 is deprecated, see https://blog.qualys.com/ssllabs/2014/09/09/sha1-deprecation-what-you-need-to-know
So, adding support for SHA-1 has a very low priority.

We have some code *fragments* for Ruby here if you want to implement an own solution:
https://github.com/Medisana/vitadock-api/tree/master/ruby

Best regards,
Clemens
